### ISSUE TITLE
mkw_classes.py errors on python 3.12.0

### ISSUE THREAD

**Issue by Gaberboo** [TASLabz/mkw-scripts#43]
```

22:29:367 Scripting/Python/Modules/doliomodule.cpp:36 E[Scripting]: Script stderr: Traceback (most recent call last):
22:29:367 Scripting/Python/Modules/doliomodule.cpp:36 E[Scripting]: Script stderr:   File "/home/gabe/.local/share/dolphin-emu/Load/Scripts/_draw_info_display.py", line 241, in on_frame_advance
22:29:367 Scripting/Python/Modules/doliomodule.cpp:36 E[Scripting]: Script stderr:     gui.draw_text((10, 10), c.color, create_infodisplay())
22:29:367 Scripting/Python/Modules/doliomodule.cpp:36 E[Scripting]: Script stderr:                                      ^^^^^^^^^^^^^^^^^^^^
22:29:367 Scripting/Python/Modules/doliomodule.cpp:36 E[Scripting]: Script stderr:   File "/home/gabe/.local/share/dolphin-emu/Load/Scripts/_draw_info_display.py", line 109, in create_infodisplay
22:29:367 Scripting/Python/Modules/doliomodule.cpp:36 E[Scripting]: Script stderr:     speed = core.get_speed()
22:29:367 Scripting/Python/Modules/doliomodule.cpp:36 E[Scripting]: Script stderr:             ^^^^^^^^^^^^^^^^
22:29:367 Scripting/Python/Modules/doliomodule.cpp:36 E[Scripting]: Script stderr:   File "/home/gabe/.local/share/dolphin-emu/Load/Scripts/Modules/mkw_core.py", line 84, in get_speed
22:29:367 Scripting/Python/Modules/doliomodule.cpp:36 E[Scripting]: Script stderr:     x = classes.VehiclePhysics.pos().x - classes.VehicleDynamics.pos().x
22:29:367 Scripting/Python/Modules/doliomodule.cpp:36 E[Scripting]: Script stderr:         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:29:367 Scripting/Python/Modules/doliomodule.cpp:36 E[Scripting]: Script stderr:   File "/home/gabe/.local/share/dolphin-emu/Load/Scripts/Modules/mkw_classes.py", line 1369, in pos
22:29:368 Scripting/Python/Modules/doliomodule.cpp:36 E[Scripting]: Script stderr:     return read_vec3(VehiclePhysics.instance(playerIdx) + 0x68)
22:29:368 Scripting/Python/Modules/doliomodule.cpp:36 E[Scripting]: Script stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:29:368 Scripting/Python/Modules/doliomodule.cpp:36 E[Scripting]: Script stderr:   File "/home/gabe/.local/share/dolphin-emu/Load/Scripts/Modules/mkw_classes.py", line 86, in read_vec3
22:29:368 Scripting/Python/Modules/doliomodule.cpp:36 E[Scripting]: Script stderr:     return vec3(x, y, z)
22:29:368 Scripting/Python/Modules/doliomodule.cpp:36 E[Scripting]: Script stderr:            ^^^^^^^^^^^^^
22:29:368 Scripting/Python/Modules/doliomodule.cpp:36 E[Scripting]: Script stderr: TypeError: vec3() takes no arguments

```

**Comment by malleoz** [comment]
This may not be relevant, as my latest PR gets rid of mkw_classes,py and moves the vec3 definition to common.py

**Comment by Gaberboo** [comment]
I just discovered it is a python bug https://github.com/python/cpython/issues/110279
